config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'matches#top'

  resources :matches
   get "/top", to: "matches#top"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord

# ルームIDは7桁
  with_options presence: true do
    validates :room_id, length: { maximum: 7, minimum: 7 }, uniqueness: true
  end


  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ユーザー名の制約
    with_options presence: true do
      validates :name, length: { maximum: 18 }, uniqueness: true
    end
  
  # メールアドレスの制約
    VALID_EMAIL = /\A\S+@\S+\.\S+\z/.freeze
    validates :email, uniqueness: true, format: { with: VALID_EMAIL }
  
  # パスワード設定の制約
    VALID_PASSWORD = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates  :password, confirmation: true, format: { with: VALID_PASSWORD }
    validates  :password_confirmation, presence: true


  has_many :matches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!, only: [:new,:show]
  before_action :set_match, only: [:show,:edit,:update]
  
  def index
    @matches = Match.all
  end

  def new
   @match = Match.new
  end

  def create
   @match = Match.new(match_params)

    if @match.save
     redirect_to root_path
    else
     render :new
    end
  end

  def show
    @match = Match.find(params[:id])
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])

    if @match.update(match_params)
      redirect_to matches_path
    else
      render :new
    end
  end

  def destroy
    match = Match.find(params[:id])
    
   if match.destroy
    redirect_to matches_path
   end

  end

  private
   def match_params
    params.require(:match).permit(:room_id, :inning,:speed,:retire,:spirits,:memo).merge(user_id: current_user.id)
   end

   def set_match
    @match = Match.find(params[:id])
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = ja, class = "h-100">
  <head>
    <title>Matchball</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "d-flex h-100 text-center">
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/matches/edit.html.erb
<%= form_with(model: @match,　local: true) do |f| %> 

<div class="row g-5">
  
  <div class="col-md-7 col-lg-8">
    <h4 class="mb-3">ルーム戦修正</h4>
    <form class="needs-validation" novalidate="">
      <div class="row g-3">

        <div class="col-12">
          <label for="room-id" class="form-label">ルームID<span class="text-muted">(7桁)</span></label>
          <%= f.text_field :room_id, class:"form-control", id:"room-id", placeholder:"ルームIDを入力してください" %>
        </div>

        <div class="col-12">
          <label for="inning" class="form-label">イニング数</label>
           <%= f.select :inning,['---','1回','2回','3回','6回','9回','タイブレイク'],class:"form-select", id:"inning", required:"" %>
        </div>

        <div class="col-12">
          <label for="speed" class="form-label">投球カーソル</label>
          <%= f.select :speed,['---','フェード','高速フェード','超高速フェード','非表示'],class:"form-select", id:"speed", required:"" %>
         </div>

        <div class="col-12">
          <label for="retire" class="form-label">強制リタイア</label>
          <%= f.select :retire,['---','有', '無'],class:"form-select", id:"retire", required:"" %>
         </div>

        <div class="col-12">
          <label for="spirits" class="form-label">スピリッツ一律</label>
          <%= f.select :spirits,['---','一律', '一律ではない'] ,class:"form-select", id:"spirits", required:"" %>
         </div>

        <div class="col-12">
          <label for="memo" class="form-label">主催者からのメッセージ</label>
          <%= f.text_area :memo, class:"form-control", id:"memo"%>
        </div>

      <button class="w-100 btn btn-primary btn-lg" type="submit">修正する</button>
    </form>
  </div>

         <%= link_to "トップページに戻る", root_path ,class:"mt-3"%>
</div>

<% end %>

app/views/matches/index.html.erb
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">主催者名</th>
      <th scope="col">ルームID</th>
      <th scope="col">イニング数</th>
      <th scope="col">スピード</th>
      <th scope="col">リタイア有無</th>
      <th scope="col">スピリッツ統一設定</th>
      <th scope="col">主催者からのメッセージ</th>
      <% @matches.each do |m|%>
       <% if user_signed_in? %>
        <% if current_user.id == m.user_id %>
         <th scope=""></th>
        <% end %>
       <% end %>
      <% end %>
    </tr>
  </thead>
  <tbody>
   <% @matches.each do |m|%>
    <tr>
      <th scope="row"><%= "#{m.user.name}"%></th>
      <td><%= "#{m.room_id}"%><br><%= "投稿日：#{m.updated_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[m.updated_at.wday]}) %H:%M")}"%></td>
      <td><%= "#{m.inning}"%></td>
      <td><%= "#{m.speed}"%></td>
      <td><%= "#{m.retire}"%></td>
      <td><%= "#{m.spirits}"%></td>
      <td><%= "#{m.memo}"%></td>
       <% if user_signed_in? %>
        <% if current_user.id == m.user_id %>
          <td><%= link_to "編集", edit_match_path(m.id), class:"btn btn-info ps-3" %></td>
          <td><%= link_to '削除', match_path(m.id), method: :delete,class:"btn btn-danger pe-3" %></td>
        <% end %>
       <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/matches/new.html.erb
<%= form_with(model: @match, url: matches_path, local: true) do |f| %> 

<div class="row g-5　mb-5">
  
  <div class="col-md-7 col-lg-8">
    <h4 class="mb-3">ルーム戦作成</h4>
    <form class="needs-validation" novalidate="">
      <div class="row g-3">
        <h6 class="mb-5">注意点：ルームIDは7桁を入力ください。それ以外は任意です。</h4>
        <div class="col-12">
          <label for="room-id" class="form-label"><span class="btn-danger">必須</span> ルームID <span class="text-muted">(7桁)</span></label>
          <%= f.text_field :room_id, class:"form-control", id:"room-id", placeholder:"ルームIDを入力してください" %>
        </div>

        <div class="col-12">
          <label for="inning" class="form-label">イニング数</label>
           <%= f.select :inning,['---','1回','2回','3回','6回','9回','タイブレイク'],class:"form-select", id:"inning", required:"" %>
        </div>

        <div class="col-12">
          <label for="speed" class="form-label">投球カーソル</label>
          <%= f.select :speed,['---','フェード','高速フェード','超高速フェード','非表示'],class:"form-select", id:"speed", required:"" %>
         </div>

        <div class="col-12">
          <label for="retire" class="form-label">強制リタイア</label>
          <%= f.select :retire,['---','有', '無'],class:"form-select", id:"retire", required:"" %>
         </div>

        <div class="col-12">
          <label for="spirits" class="form-label">スピリッツ一律</label>
          <%= f.select :spirits,['---','一律', '一律ではない'] ,class:"form-select", id:"spirits", required:"" %>
         </div>

        <div class="col-12">
          <label for="memo" class="form-label">主催者からのメッセージ</label>
          <%= f.text_area :memo, class:"form-control", id:"memo", placeholder:"誰でも参加OK!" %>
        </div>

      <button class="w-100 btn btn-primary btn-lg" type="submit">作成する</button>
    </form>
  </div>

         <%= link_to "トップページに戻る", root_path ,class:"mt-3"%>
</div>

<% end %>

app/views/matches/show.html.erb
<%# <%= @match.name%>

app/views/matches/top.html.erb
<main class = "w-100 h-100">

  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to "MatchBall", root_path,class:"display-8 navbar-brand fs-1" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end"  id="navbarNav">
            <% if user_signed_in?%>
              <ul class="navbar-nav">
                <li class="nav-item" >
                 <%= link_to "ユーザー名：#{current_user.name}", root_path,class:"display-8" %>
                </li>
                <li class="nav-item" >
                  <%= link_to "試合一覧を確認", matches_path,class:"display-8" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ルーム戦を作成する", new_match_path ,class:"display-8"%>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path ,method: :delete,class:"display-8"%>
                </li>
              </ul>
            <% else %>
              <ul class="navbar-nav ">
                <li class="nav-item">
                  <%= link_to "試合一覧を確認", matches_path,class:"display-8"%>
                </li>
                <li class="nav-item">
                  <%= link_to "ルーム戦を作成する", new_match_path ,class:"display-8"%>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path ,class:"display-8"%>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path ,class:"display-8"%>
                </li>
              </ul>
            <% end %>
        </div>
      </div>
    </nav>
  </header>

  <div class="container">
    <p class="mt-5 fs-2">ようこそ！MatchBallへ！</p>
    <p class="mt-4 fs-4">プロスピAのルーム戦のマッチングをお手伝いします！</p>
  </div>
</main>